version: '3.8'

services:

  notificador:
    build:
      context: ./notificador
    container_name: notificador
    restart: unless-stopped
    ports:
      - '3002:3002'
    networks:
      - backend-net

  processor:
    build:
      context: ./processor
    container_name: processor
    restart: unless-stopped
    networks:
      - backend-net

  processor2:
    build:
      context: ./processor
    container_name: processor2
    restart: unless-stopped
    networks:
      - backend-net

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - '80:80'
    networks:
      - backend-net
    depends_on:
      - processor
      - processor2

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    restart: unless-stopped
    ports:
      - '3000:3000'
    networks:
      - backend-net
    depends_on:
      - nginx

networks:
  backend-net:
    driver: bridge
